version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    timezone: America/Chicago
  open-pull-requests-limit: 99
  ignore:
  - dependency-name: com.fasterxml.jackson.core:jackson-databind
    versions:
    - 2.12.2
    - 2.12.3
  - dependency-name: io.netty:netty-codec
    versions:
    - 4.1.60.Final
    - 4.1.61.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-common
    versions:
    - 4.1.60.Final
    - 4.1.61.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-handler
    versions:
    - 4.1.60.Final
    - 4.1.61.Final
    - 4.1.62.Final
  - dependency-name: io.netty:netty-transport
    versions:
    - 4.1.60.Final
    - 4.1.61.Final
    - 4.1.62.Final
